name: Policy Test

on:
  push:
    branches:
      - main
      - release*
  pull_request:
    branches:
      - main
      - release*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          path: policies

      - name: Clone Kyverno
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          repository: kyverno/kyverno
          path: kyverno
          # The target branch of a pull request or the branch/tag of a push
          ref: ${{ github.base_ref || github.ref_name }}

      - name: Set up Go 
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: 1.18

      - name: Test Policy
        run: go run ./cmd/cli/kubectl-kyverno test ../policies
        working-directory: kyverno
